### ISSUE TITLE
Memory usage and analysis object

### ISSUE THREAD

**Issue by Tang-pro** [almeidasilvaf/BioNERO#20]
Hi, @almeidasilvaf 

Here I have 10 samples, three biological replicates, and the species has about 70,000 to 80,000 genes. How much memory does this require?
Second, Is it possible to analyze using isoform levels, Because I built a full-length isoform based on PacBio, I have an idea here, whether it is possible to study co-expression between isoforms, is this feasible?

Best!

**Comment by almeidasilvaf** [comment]
Hi, @Tang-pro 

According to estimated from WGCNA developers:

> (...) analyzing a set of 20,000 variables or nodes (for example, genome-wide data summarized to genes) requires between 8 and 16 GB of memory; 40,000 nodes (for example, expression data summarized to transcripts) would increase the requirement to 32-64 GB.

Your question is very timely: as a coincidence, I have just pushed a new version of BioNERO that includes a new function named `exp2gcn_blockwise()` (docs [here](https://almeidasilvaf.github.io/BioNERO/reference/exp2gcn_blockwise.html)) that allows module detection in a blockwise manner (see [this post](https://peterlangfelder.com/2018/11/25/blockwise-network-analysis-of-large-data/) for more details). The only downside is that you will not have all objects that `exp2gcn()` returns, but you will still get a data frame of module assignment for each gene. 

That said, I have never seen a case where one would infer a network from 70-80k thousand genes. This large number probably means that you're trying to infer a network from all genes in a genome, which is not right. Instead, you should filter you expression matrix first to, for instance:

1. Remove non-expressed genes and genes with very low expression;
2. Remove genes that have stable expression across samples, since most of the time one is interested in gene expression variations.

In my experience, I usually infer coexpression networks from matrices with less than 20k genes, and I work with (very large) plant genomes. 

If this answers your question, feel free to close the issue. ;)

Best,
Fabricio

**Comment by Tang-pro** [comment]
Hello, @almeidasilvaf 

Thank you very much for your detailed reply, I have filtered as per your protocol, but my question has just been updated, there is a second question here, is it possible to do the analysis on isoform level.

**Comment by almeidasilvaf** [comment]
Hi, @Tang-pro 

In theory, yes, but interpretation would not be so trivial. You would also probably need to think about your thresholds (transcript abundance is different from gene-level transcript abundance, since the latter usually involves aggregating counts per gene).

**Comment by Tang-pro** [comment]
Hi, @almeidasilvaf 
Yes，I have been thinking about this issue recently, maybe I need to think about it again, thank you again for your reply!

Good Luck!

**Comment by almeidasilvaf** [comment]
Always a pleasure to help!

I'll close this issue, then.

Best,
Fabricio
