### ISSUE TITLE
Error in Module Trait Correlations

### ISSUE THREAD

**Issue by MysoreSparrow** [almeidasilvaf/BioNERO#4]
Its an extremely useful and much required package. Thank you for the efforts in developing it. 

I think there is an error or more explanation required for the Module Trait Correlations.
The code I tried to run was : (first with an SummarizedExperiment Object)
```
# Module Trait Correlations
MEtrait <- module_trait_cor(exp = final_exp,
                            MEs = net$MEs,
                            cor_method = "pearson"
                            )
```
The error was : " Error in cor(as.matrix(MEs), trait, use = "p", method = cor_method) : 
  'y' must be numeric" .

Next, I tried to give the parameters exp and metadata as individual objects and I still ended up with the same error for the following code
```
# Module Trait Correlations
MEtrait <- module_trait_cor(exp = as.data.frame(assay(final_exp)),
                            MEs = net$MEs,
                            metadata = coldata_merged,
                            cor_method = "pearson"
                            )
```

Again the error was , Error in cor(as.matrix(MEs), trait, use = "p", method = cor_method) : 
  'y' must be numeric. 

From what I could see, the handle_trait_type() in https://github.com/almeidasilvaf/BioNERO/blob/master/R/utils.R, isnt picking up numeric values. Or may be I am missing something or doing wrong?  Any help is much appreciated. Thank you.

**Comment by almeidasilvaf** [comment]
Hi, @MysoreSparrow 

Thank you very much for your feedback!

Could you try to create a [reprex](https://reprex.tidyverse.org/) so I can try to run the same code? As I don't have access to your data (e.g., objects `final_exp` and `coldata_merged`), I can't find what is causing the issue.

If I could guess, it'd say it is probably related to the structure of your metadata data frame (`colData` in your `SummarizedExperiment` object). __BioNERO__ uses the first column of your `colData` as the trait variable, so if your trait variable is in another column, it wouldn't work. Is that your case? Is your trait variable in a column other than the first column?

**Comment by MysoreSparrow** [comment]
Thank you very much for your help and the quick response. I attach the html file (hopefully it gives you an idea of what is wrong) and also the resoective R script is in : https://github.com/MysoreSparrow/AZB_DataAnalysis/blob/main/BioNERO.R . 

Please see page 21 and 22 in the pdf.
[BioNERO.R.pdf](https://github.com/almeidasilvaf/BioNERO/files/10489125/BioNERO.R.pdf)

**Comment by almeidasilvaf** [comment]
Hi, @MysoreSparrow 

It seems that your metadata data frame is not formatted as it should be. See the help page for the function (`?module_trait_cor`):

> metadata  A data frame containing sample names in row names and sample annotation in the first column. Ignored if 'exp' is a 'SummarizedExperiment' object, since the function will extract colData.

As stated in the function docs, the rownames of your data frame should be sample names (same as the column names of the gene expression matrix), and the first column should contain sample information. Your `coldata_merged` object looks like this:

```r
coldata_merged
#>     Sample_Name Epithelial_response
#> T             T                   0
#> S54         S54                   0
#> S55         S55                   1
#> L57         L57                   1
```

As you already have samples names in row names, you only need to remove the column "Sample_Name":

```r
coldata2 <- coldata_merged[, "Epithelial_response", drop = FALSE]
coldata2
#>     Epithelial_response
#> T                     0
#> S54                   0
#> S55                   1
#> L57                   1
```

Notice, however, that __BioNERO__ will use the internal function `handle_trait_type()` to create a matrix where each level of the variable "Epithelial_response" will become a column of module-trait correlation plot. As you assigned numbers (0 and 1) to each level, it will be hard for you to interpret the results, I think. Using the `coldata2` data frame I created above, the matrix (and, hence, your heatmap) will look like this:

```r
BioNERO:::handle_trait_type(coldata2)
#> 
#>     X0 X1
#> L57  0  1
#> S54  1  0
#> S55  0  1
#> T    1  0
```

X0 corresponds to level "0" and X1 to level "1". Not very nice, huh? I would suggest converting the numbers to comprehensible characters. For example:

```r
coldata2$Epithelial_response <- ifelse(
    coldata2$Epithelial_response == 1, 
    "Responsive",
    "Non_responsive"
)
coldata2
#>     Epithelial_response
#> T        Non_responsive
#> S54      Non_responsive
#> S55          Responsive
#> L57          Responsive

BioNERO:::handle_trait_type(coldata2)
#>     Non_responsive Responsive
#> L57              0          1
#> S54              1          0
#> S55              0          1
#> T                1          0
```

This is way better.


If your problem was solved, please feel free to close this issue.

**Comment by MysoreSparrow** [comment]
Hello @almeidasilvaf ,

Firstly, thank you for taking the time and for the detailed response. I made the changes as per your earlier comment. 

I now have all the objects formatted as it should be, and I still have the same error, for which I raised this issue.

Just to be sure: 

My colData in the SE object now looks like below and I believe that should take care of the one-hot encoding issue, as you wrote above. 
```
final_exp@colData
DataFrame with 14 rows and 2 columns
    Epithelial_response clinical_outcome
            <character>      <character>
T            LowInducer      symptomatic
S54          LowInducer      symptomatic
S55         HighInducer      symptomatic
L57         HighInducer           Lethal
A58          LowInducer     asymptomatic
```
My coldata_merged is : 
```
head(coldata_merged)
     NleA_1 clinical_outcome
T    Absent      symptomatic
S54  Absent      symptomatic
S55  Absent      symptomatic
L57  Absent           Lethal
A58  Absent     asymptomatic
L60 Present           Lethal
```

I now run : 

```
MEtrait <- module_trait_cor(exp = final_exp,
+                             MEs = net$MEs,
+                             metadata = coldata_merged,
+                             cor_method = "pearson",
+                             continuous_trait = FALSE
+                             )
Error in cor(as.matrix(MEs), trait, use = "p", method = cor_method) : 
  'y' must be numeric
```
I am sorry to bother you again but this was important to me that I should be able to obtain these module trait correlations.

**Comment by almeidasilvaf** [comment]
Hi, @MysoreSparrow 

Again, as described in the function docs, the metadata data frame can only contain one column. Your data frame has 2 columns. I will add a check to return an error message the data frame has more than 2 columns.

If you want to repeat the analysis for multiple variables, you can loop through them.

Could you confirm that using an one-column data frame works?

**Comment by MysoreSparrow** [comment]
Hi @almeidasilvaf , Yes I can confirm that with ONLY one column in metadata, the module_trait_cor() works! Thank you for your help and time. The documentation said that first column must be Sample annotation, which I would suggest I believe is slightly mis-leading. I suggest you could change that to read as ONLY column to be present. 

Secondly, most tasks would require correlations with multiple columns so it kind of becomes bit of a dampener that function could handle only column at a time - otherwise its an extremely useful package. Would be wonderful if you could extend that to include multiple columns. In my case I have 58 columns of metadata that I would like to find correlations between modules and traits (of metadata) .

**Comment by almeidasilvaf** [comment]
Thank you for confirming, @MysoreSparrow 

Indeed, I will make it more clear in the docs that it works only one variable at a time. 

And thank you for your suggestion on allowing multiple columns. I had already thought about that. The problem is that the function returns a heatmap and a data frame with correlations and P-values. One can loop through each column, but each time the function is executed, the heatmap for variable n would be replaced with the heatmap for variable n+1. FYI, if you have a metadata data frame named `coldata` with 2+ columns and an expression matrix named `exp`, you could do that with:

```r
# Create a vector from column 2 to last column
idx <- 2:ncol(coldata)

cor_list <- lapply(idx, function(x) {
    MEtrait <- module_trait_cor(exp = exp, MEs = net$MEs, metadata = coldata[, x, drop = FALSE], cor_method = "pearson")
    return(MEtrait)
})
```

I could try to combine all levels of every variable in a single heatmap, but the heatmap would have so many columns that it wouldn't be readable. Take your case, for example: if you have 58 columns, and assuming every column is binary (two levels), the heatmap would have 116 columns. That is sufficient to make it unreadable. I will try to think of a solution for that.

What you can also try is combine some variables into a single one. For instance, if you have a variable `Treatment` with levels "control" and "infected" and a variable `Timepoint` with time in hours, you could create a variable "Treatment_time" that combines both information.

Is there anything else I could help you with?

**Comment by MysoreSparrow** [comment]
Hi @almeidasilvaf ,

You're spot-on with regard to cluttered and dense-looking heatmaps. Mine is a bit of an extreme case with 58 columns but I would guess that most people would be happy to be allowed 5 columns at max. 

In regard to allowing multiple columns, yes I also thought of using lapply - thank you for putting up the code for it. Anyone else reading this later would certainly be benefitted. 
I'm sure you're aware of putting the DF and heatmap from every iteration into a container object - though that makes it a bulky and time-consuming affair but its still worth it I guess. 

Your responses have been very quick and helpful. Thank you again for that. I will close this issue.
