### ISSUE TITLE
module_trait_cor with continuous_trait = F can only handle 1 trait variable?

### ISSUE THREAD

**Issue by jucapitanio** [almeidasilvaf/BioNERO#9]
Hey all,

I've been playing around with your package a bit more and I realized that module_trait_cor with continuous_trait = F can only handle 1 trait at a time. I think this is due to how handle_trait_type creates the contrast matrix.
It's easy to get around this with the map functions from purrr, but I thought I'd let you know. Maybe it might be a good idea to indicate this in the vignette? Or maybe I'm just using it wrong... I don't see the same issue when using multiple numeric traits, fyi.

Thanks again for the great package.

**Comment by almeidasilvaf** [comment]
Hi, @jucapitanio 

This issue is likely a duplicate of issue #4. 

Indeed, for categorical variables, one can only do it one column at a time. That is because when you use categorical variables, you calculate module-trait correlations for each level of the categorical variable. Hence, if you have 5 columns with categorical variables and each of them has 5 levels, you would have a heatmap of module-trait correlations with 25 columns. 

As you rightly pointed out, looping through columns is the way to go, as I replied [here](https://github.com/almeidasilvaf/BioNERO/issues/4#issuecomment-1402346513). The problem is that `module_trait_cor()` returns both a data frame of module-trait correlations + P-values and a plot, which is produced with a function imported from the WGCNA package that uses the base R plotting system. Since base R plots cannot be stored in objects (as ggplots and *grid* objects can, for instance), calling the function several times in a loop would replace one plot with another after each iteration, but you would still have the data frames of correlations and P-values.

FYI, I'm planning to release a major update within the next weeks that will replace all plots produced with the base plotting system (mostly the ones that rely on WGCNA plotting functions) with functions that use the *grid* plotting system. This way, the output of functions like `module_trait_cor()` could be a list of length 2 containing the data frames of correlations + P-values, and the heatmaps. This would allow using multiple columns in `module_trait_cor()`.

Best,
Fabricio

**Comment by jucapitanio** [comment]
Thanks for the detailed reply Fabricio. I appreciate you taking the time and totally understand why you made that choice. I just meant that it might be a good idea to add a small side note to the vignette indicating the function works differently with different variable types. I normally use R notebooks, so iterating over your current function with purrr::map works well and keeps all created plots in the Rmd file. I look forward to the update!
PS: Sorry for the duplicate issue.

**Comment by almeidasilvaf** [comment]
Multiple columns are now allowed in v1.9.2.
